-- 코드를 작성해주세요
select YEAR(DIFFERENTIATION_DATE) as YEAR, b.MAX_SIZE - a.SIZE_OF_COLONY as YEAR_DEV, a.ID
from ECOLI_DATA as a , (select YEAR(DIFFERENTIATION_DATE) as YEAR, max(SIZE_OF_COLONY) as MAX_SIZE from ECOLI_DATA group by YEAR(DIFFERENTIATION_DATE)) as b
where b.YEAR = YEAR(DIFFERENTIATION_DATE)
order by 1, 2;

