-- 코드를 작성해주세요
SELECT
A.ID, B.FISH_NAME, A.LENGTH as LENGTH
FROM FISH_INFO AS A
    INNER JOIN FISH_NAME_INFO AS B
    ON A.FISH_TYPE = B.FISH_TYPE
where (A.LENGTH, B.FISH_NAME) in (SELECT
    max(A.LENGTH), B.FISH_NAME
    FROM FISH_INFO AS A
        INNER JOIN FISH_NAME_INFO AS B
        ON A.FISH_TYPE = B.FISH_TYPE
    GROUP BY B.FISH_NAME)
order by 1;