-- 코드를 입력하세요
SELECT
CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS B
    INNER JOIN BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID
where s.SALES_DATE between '2022-01-01' and '2022-01-31'
group by 1
ORDER BY 1;